Orange Islands Overhaul
Rangi42/polishedcrystal pull request #919
Opened 2023-12-21 06:00 UTC by katedering

This aims to properly cement Orange Islands as the 'de facto' endgame area, by both boosting the badge-base-level curve to cap at 68 instead of 61, and by drastically boosting the level of the wild Pokemon in Orange Islands. Additionally this adds the badge system to every trainer there and adds parties to the TODO bulbasaur trainers.

2023-12-22 00:16 UTC, Rangi42 requested changes
Thanks, but these look unusually high. From the other `LEVEL_FROM_BADGES` uses in trainer parties, even `+ 10` is on the high end for non-boss trainers (and lower for wild mons, even with `-`s).

2023-12-22 00:18 UTC, katedering commented
I could drop the wild levels a bit but it never made sense to me that an area that you unlock post-e4 had wild encounters in the low-mid 30s, where most of Kanto has it in the 50s and up.

2023-12-22 01:04 UTC, katedering commented
![image](https://github.com/Rangi42/polishedcrystal/assets/26468141/aa990fd1-c95d-4211-a365-54249e13da52)
this is the average wild level after ten badges, about the same as kanto's wild range in general

2024-11-27 15:06 UTC, katedering commented
![orange](https://github.com/user-attachments/assets/3d32860f-fa16-4d3e-99f6-dc0e0854d135)

This is the first trainer in Orange Islands, encountered as soon as you reach Kanto. For reference, her team in base 9bit is two Level 55 Bellossom. The level range is exactly the same as default Polished 9bit IF you go there immediately after arriving in Kanto, even with the 'unusually high' level range, so I still think this is fine to push as-is.

2025-03-01 05:11 UTC, itsdarsh commented on data/trainers/parties.asm
> +	dbp LEVEL_FROM_BADGES + 30, BELLOSSOM, FEMALE
I mean this more to be illustrative than to imply this is the only issue: I don't think it's a good idea to have a random trainer with a Level 98 Bellossom.

2025-03-01 05:12 UTC, itsdarsh commented
If you could separate your move fixes from the trainer and wild pokemon changes, I can merge those right away. Thanks for fixing those!

2025-03-07 23:29 UTC, katedering commented on data/trainers/parties.asm
> +	dbp LEVEL_FROM_BADGES + 30, BELLOSSOM, FEMALE
That /one/ specific trainer may be a bit high yes, but, again, overall the level curve is about the same as vanilla if you go there right upon unlocking Kanto.

2025-03-07 23:31 UTC, katedering commented
what would be the easiest way to do that, close this and put it up as 2 different PRs?

2025-03-07 23:44 UTC, closed without merging

2025-03-07 23:44 UTC, katedering commented
Closing for now, will PR the moves.asm commit as a separate one.